name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/KnutGame.Client/package-lock.json

      - name: Install client deps
        working-directory: src/KnutGame.Client
        run: npm ci

      - name: Build client (generates manifest)
        working-directory: src/KnutGame.Client
        run: npm run build

      - name: Run client tests
        working-directory: src/KnutGame.Client
        run: npm test -- --run

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release
